### ISSUE TITLE
Documentation, How to install

### ISSUE THREAD

**Issue by juancarlospaco** [dsrw/enu#1]
How to install it?, I tried nimble install and checking the code, but I think is referencing a folder outside of the repo (?),
also nimble only considers Windows and Mac, no Linux support ?, documentation about how to install is needed.
:)

**Comment by dsrw** [comment]
I haven't tested on Linux yet. I assume the most recent Ubuntu release would be a reasonable place to start?

I'll try to get some install docs up in the next day or two. Thanks!

**Comment by geekrelief** [comment]
I had issues getting it running on Windows too.  When running the 'nimble generate' task I ran into a nimscript error:

```
C:\Users\geekr\AppData\Local\Temp\nimblecache\nimscriptapi.nim(165, 16)
C:\godot\enu\enu_8084.nims(39, 8) generateTask
C:\Users\geekr\scoop\apps\nim\current\lib\system\nimscript.nim(186, 19) exec
C:\Users\geekr\scoop\apps\nim\current\lib\system\nimscript.nim(186, 19) Error: unhandled exception: The system cannot find the file specified.
 [OSError]
     Error: Exception raised during nimble script execution
```
 I got passed this by copying the godotapi I generated from the godot-nim-stub, and I was able to get things running.
