### ISSUE TITLE
Color on cubes forgotten

### ISSUE THREAD

**Issue by juancarlospaco** [dsrw/enu#10]
- Make a RED cube and edit its script with:

```nim
import grid
up()
```

- New BLUE cube appears on top, I do not know if this is intended or bug ?.

**Comment by dsrw** [comment]
It's not intended. There are a few other issues that are somewhat related:

- Build a structure out of red blocks. After restarting, the first block will be blue (the rest stay red).
- Build a structure. Remove the first block you placed. After restarting, the first block will return, and it will always be blue.

**Comment by dsrw** [comment]
Fixed

**Comment by juancarlospaco** [comment]
Awesome!, when I have some free time I have to check the new improvements,
the Enu presentation video was awesome. 🙂:+1:

**Comment by dsrw** [comment]
Thanks! 0.2 will be out soon. Before the end of the month.
