### ISSUE TITLE
Color Bots

### ISSUE THREAD

**Issue by juancarlospaco** [dsrw/enu#11]
Add Bots of color, just like the cubes, so you can make 2 "AI" scripts, kinda red team Vs blue team.

**Comment by dsrw** [comment]
There will be an inventory in the future, which will make it easier to add different object types. It will also be possible to add your own creations by assigning a `name` property in the script. Ex. build a house, open the script and write `name = "house"`, and a house shows up in your inventory that can be placed anywhere. You'll also be able to `import house` from other scripts to place it via code, or call procs and such.

For now, is it enough to say `color = red` in the bot's script? This doesn't work currently, but it's easy to add.

**Comment by juancarlospaco** [comment]
Oh, I see theres a better idea!, then closing this...
:)
