### ISSUE TITLE
Falling of the world

### ISSUE THREAD

**Issue by juancarlospaco** [dsrw/enu#12]
- Double tap Space to fly.
- Press <kbd> C </kbd> and hold it.
- You pass thru the floor and keep falling forever.
- World moves away quickly so you dont notice you fallen from the world.

If you walk to the world border you also fall of the world too, 
maybe world border should have an invisible wall or teleport you to the center again, whatever is easier to implement.

Maybe a key to teleport you to the center of the world can be cool too.

**Comment by dsrw** [comment]
At some point the console (toggled with `~`) will be a REPL, and there will be a `teleport` proc that can be used from the REPL or from scripts. That probably won't be for a few releases though. It will also be be possible to cycle through all of the structures/objects in a world with some sort of key binding, which will teleport you to the object and bring up its code. So, long term there I don't think there will be a "teleport to the center of the world" key binding, but I can add one temporarily if you think it would be useful. Thoughts on what the key combo should be?

Flying through the floor should be an easy fix. Flying disables collisions, but I think I can leave them enabled for the floor. 

I think I'll auto-teleport to the center of the world if the y axis goes past -100, or some other threshold, which should take care of the "falling off the world" problem.

**Comment by juancarlospaco** [comment]
Just leave floor collision enabled when flying.
