### ISSUE TITLE
Question: Is it possible to get x,y from block?

### ISSUE THREAD

**Issue by inv2004** [dsrw/enu#14]
Hello,

1st: Thank you for the windows-version. I think it makes setup to kids' laptop much easier.

I want to build something like wall in loop. I do up() every iteration, but, I did not find easy way to return to start point?

Thank you,

**Comment by dsrw** [comment]
You can't currently get or set x, y, z coordinates from a block. I plan to implement it at some point, but I don't think it will be in the next release. Possibly the one after that (0.3).

However, you can `save()` your current position, direction, and color, then `restore()` it later. So, to build a wall, you could do something like this:

```nim
10.times:
  save()
  forward 10
  restore()
  up()
```

You can also give the save and restore points names, if you need to manage more than one:

```nim
8.times:
  save "start"
  10.times:
    save()
    forward 10
    restore()
    up()
  restore "start"
  turn_right 45
```

![image](https://user-images.githubusercontent.com/1416/113743385-ffe1f480-96d9-11eb-90b0-98f9e5664023.png)

Thanks for the question. I hope that helps.
