### ISSUE TITLE
Preview Release status

### ISSUE THREAD

**Issue by fikriauliya** [dsrw/enu#23]
> unstable to the point of being unusable. A preview release will be available by the end of Feb 2022.

I am thinking to use Nim + Enu to teach basic programming to 400s students next week (I am exploring Nim this weekend, figuring it out whether it's suitable for teaching purpose)

Since end of Feb is just around the cornet :D, I wonder whether current `main` branch is usable enough now?

**Comment by dsrw** [comment]
Yes, it should be fairly stable. There are a few minor issues still to work out, but the main tasks now are updating the docs and putting the release builds together.  I haven't actually tried building on Linux and Windows in almost year, so I expect issues there.

What platform are you using? I can try to get a prerelease build out this evening if you tell me what you need.

**Comment by dsrw** [comment]
To elaborate a bit on the state of things, there are still lots usability issues, but they're mostly targeted for the next release (0.3). Table stakes type functionality like switching worlds or changing your font size requires editing a config file. There's no in-game help. It's not possible to resize the editor pane or the action bar.  I do think it's at the point where it could be a useful teaching tool, but there are still a lot of rough edges.

**Comment by fikriauliya** [comment]
Thank you for your warm response :).

I reconsidered the audience and seems they are not ready for Nim (it's totally new for them, and the language spec is not as small as I was expecting). Finally I decided to go with JS.

Nevertheless, this is cool project. I would like to try on my 6 year sometimes next week :D (he enjoys playing Scratch and building game with Nintendo Game Garage).

**Comment by dsrw** [comment]
[Enu 0.1.97](https://github.com/dsrw/enu/releases/tag/v0.1.97) has finally been released. There are still a few features to complete and a lot of testing that needs to be done for 0.2, but most of the functionality is there. Thanks for taking an interest!
