### ISSUE TITLE
Automated builds

### ISSUE THREAD

**Issue by theoparis** [dsrw/enu#24]
It seems that there isn't a latest linux build  for 0.1.98. On my machine it still takes a long time to compile, which is unfortunate. This could be solved by adding a github actions yml file to automatically build and/or release builds upon pushing new commits.  The nice thing about using github actions is that its reliable and you can create windows, macos and linux builds automatically without needing to own the hardware.

I was experimenting with this in my fork, however I haven't managed to get it to work yet.

**Comment by dsrw** [comment]
0.1.99 will be out this week and will include a Linux build. You're right though, it really should be automated. I'll try to look into it soon. Definitely feel free to submit a PR with what you have, even if it doesn't work.

**Comment by dsrw** [comment]
Just FYI, but the build is still somewhat broken. Enu depends on https://github.com/nim-lang/Nim/pull/19182, which isn't part of a stable nim version yet. I think it should be possible to build with vanilla 1.6.4, but it will need the changes to `macros.nim` from that PR at runtime. `nimble prereqs` needs to be updated to deal with this, but I haven't gotten to it yet.

**Comment by dsrw** [comment]
You can now download a CI build for macOS, Windows, and Linux at https://github.com/dsrw/enu/actions. I haven't actually tried the Linux build unfortunately, but I think it should work.
