### ISSUE TITLE
AppImage for Linux

### ISSUE THREAD

**Issue by moigagoo** [dsrw/enu#25]
Hi!

AppImage [1] is a relatively new package format for Linux that it particularly handy for games.

The cool thing about it is that all the right versions of the dependencies are in the package. For example, I can't run Enu on my current distribution because Enu requires glibc 2.34 whereas the repos only offer 2.33.

1: https://en.wikipedia.org/wiki/AppImage

**Comment by dsrw** [comment]
Sounds good to me. Thoughts on Snap and Flatpak? Is AppImage alone enough to support most Linux users, or should I offer one/both of the other formats as well?

**Comment by moigagoo** [comment]
AppImage is the way to go, forget about Snap or Flatpak. From my experience, only AppImage is truly portable.

**Comment by dsrw** [comment]
There's now an AppImage built as part of CI, and it will be included in the next release. There's a build here: https://github.com/dsrw/enu/actions/runs/4768970337. 

It doesn't include any library dependencies, but Godot apps statically link pretty much everything, so I think that should be ok. I also switched the build to an older Ubuntu version, which should help with glibc issues.

Please reopen the ticket if you run into any problems. Enu is partially broken ATM, so expect bugs, but I think the AppImage should work as well as any other version.

**Comment by dsrw** [comment]
NVM, the AppImage still has problems. I'll have it sorted soon.

**Comment by dsrw** [comment]
I was hitting a race condition unrelated to the AppImage. I think the AppImage is working properly, and the race condition has been fixed.
