### ISSUE TITLE
Great work! I have to ask how to quit the game.

### ISSUE THREAD

**Issue by xjzh123** [dsrw/enu#30]
When I launch with the default fullscreen mode in Windows 11, I can't find how to quit or exit the game. I had to launch task manager to stop the process. Hope I haven't missed some documention.

**Comment by xjzh123** [comment]
Also, I find `F` not working, and don't know how to type in the console with `~`...

**Comment by dsrw** [comment]
Thanks! Sorry about the issue with the docs. Ctrl+Q will quit on windows, and Alt+Enter will toggle between fullscreen and windowed mode. I'll fix the docs a little later today.

The console is just for log messages at the moment, it doesn't take input. I plan to change this, but I'm not sure of the timeline. I created an issue to track it.  https://github.com/dsrw/enu/issues/31

**Comment by dsrw** [comment]
@xjzh123 Thanks for the bug report! I updated the docs to contain the correct keybinding for `toggle fullscreen`, and added a new entry for `quit`. Please let me know if you encounter any more doc errors!
