### ISSUE TITLE
Bigger Bullseye

### ISSUE THREAD

**Issue by juancarlospaco** [dsrw/enu#8]
Mouse pointer "bullseye" indicator that points to the current block hovered is kinda small, fades away too quickly if it is slightly far,
a bigger one would be more explicit to know the currently hovered block. 

An alternative can be same bullseye icon but with some kind of "effect", whichever is easier to implement.

**Comment by dsrw** [comment]
It also basically disappears on lighter colors. I'll bump up the size a bit and see if I can do an XOR type inverse color effect.

Totally unrelated, but how do you feel about about the linux packaging situation? I don't think I want to get into distro specific packages right now, but is it worth setting up an appimage, snap or flatpak?

**Comment by juancarlospaco** [comment]
Linux works Ok, I just downloaded, uncompressed, run the binary from terminal, it runs.
